# Generated by Django 5.0.3 on 2024-04-21 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='company_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='images/company_logos/')),
                ('website_url', models.TextField(blank=True, null=True)),
                ('company_subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_eastablishment', models.PositiveIntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_copy', models.ImageField(blank=True, null=True, upload_to='images/license_copies/')),
                ('company_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_email', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_address', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='images/id_pics_front/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='images/id_pics_back/')),
                ('company_size', models.CharField(choices=[('1-50', '1-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-2000', '1001-2000'), ('2001-5000', '2001-5000'), ('5001+', '5001+')], default='1-50', max_length=10)),
                ('business_desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.category')),
                ('company_type', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.company_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('license_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.license_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('job_desc', models.TextField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('company_info', models.CharField(blank=True, max_length=100, null=True)),
                ('compensation', models.CharField(blank=True, max_length=200, null=True)),
                ('other_facilities', models.TextField(blank=True, null=True)),
                ('apply_procedure', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.category')),
                ('company_type', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.company_type')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.service_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
