# Generated by Django 5.0.3 on 2024-04-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='license_type',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='company_owner',
            new_name='representative_designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_address',
            new_name='representative_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_designation',
            new_name='representative_mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='company_name',
            new_name='representative_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_mobile',
        ),
        migrations.DeleteModel(
            name='License_type',
        ),
    ]
