# Generated by Django 4.2.1 on 2024-03-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_company_type_license_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='designation',
            new_name='job_designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
