# Generated by Django 4.2.1 on 2024-03-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_designation_job_post_job_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='company_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.company_type'),
        ),
    ]
