# Generated by Django 5.0.3 on 2024-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_job_post_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='company_title',
        ),
        migrations.AddField(
            model_name='job_post',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
